name: CodeCov

on:
  push:
    branches:
      - master

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up JDK 17
        uses: actions/setup-java@v1
        with:
          java-version: 17

      - name: Set project directory permissions
        run: chmod -R +xw .

      - name: Set up GCC
        uses: egor-tensin/setup-gcc@v1
        with:
          version: latest
          platform: x64

      - name: Verify GCC installation
        run: gcc --version

      - name: Compile C program
        run: gcc -o my_program test_files/c_out/cFileTest.c

      - name: List files
        run: ls -la

      - name: Build with Maven
        run: mvn clean package

      - name: Run JUnit tests and generate coverage report
        run: |
          mvn test jacoco:report
          mvn jacoco:report-aggregate

      - name: Upload coverage report to Codecov
        uses: codecov/codecov-action@v3
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
